# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

mysql:
    type: mysql:10.0
    disk: 2048

redis:
    type: redis:3.0

search:
    type: elasticsearch:2.4
    disk: 1024
    configuration:
        plugins:
            - analysis-icu
            - analysis-phonetic